config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :relationships
 
  root 'pages#index'
  post 'toggle' => 'likes#toggle_like'
  get '/home' => 'pages#home'
  get '/search' => 'posts#search'
  post 'user/pages/relation' => 'pages#relation'
  get '/user/:id' => 'pages#profile'
  get '/user/:id/following' => 'pages#following'
  get '/user/:id/followers' => 'pages#followers'
  get '/user/:id/likes' => 'pages#likes'
  post '/user/:id/pages/relation' => 'pages#relation'
  post '/theme_submit' => 'pages#theme_submit'
  post '/new' => 'comments#new'
  get '/comments' => 'comments#comment'
  get '/theme' => 'pages#theme'
  get '/explore' => 'pages#explore'
  get '/upload_image' => 'pages#upload_image'
  get '/upload_cover_image' =>'pages#upload_cover_image'
  post '/upload_image_submit' => 'pages#upload_image_submit'
  post '/upload_cover_image_submit' => 'pages#upload_cover_image_submit'
  
  get '/pages/developer'

end

app/views/pages/_following.html.erb
<div class="col-xs-4">
	<div class="shadow follower-panel panel panel-default">
			<div class="profile-short-banner">
				<img src="/uploads/<%=User.find_by_id(following).profile_picture%>" class="avatar-panel">
			</div>
			<% if following != current_user.id %>
				<form action="/user/pages/relation" method="POST">
					<input type="hidden" name="followee_id" value="<%=following%>"/>
        			
        			<% if Relationship.where(follower_id: current_user.id , followee_id: following).count>0 %>
						<button class="relation">
							<span class="relation-text">UnFollow</span>
						</button>
					<% else %>
						<button class="relation">
							<span class="relation-text">Follow</span>
						</button>
					<% end %>
				</form>
			<% end %>
			<div class="avatar-name"><b><%=User.find_by_id(following).username%></b></div>
	</div>
</div>
		

app/views/pages/_post.html.erb
<div class="panel panel-default form-panel" id="post-contents">			
  			<div class="panel-body row">
  				<div class="col-sm-1">
  					<img src="/uploads/<%= User.find_by_id(tweet.user_id).profile_picture %> " class="round-image" height="50px" width="50px">
  					</img>
  				</div>
  				<div class="col-sm-11">
  					<p class="post-title"><span class="post-owner"><a href="/user/<%=User.find(tweet.user_id).username%>"><%=User.find(tweet.user_id).username%></a></span><span class="post-creation"> - <%=time_ago_in_words(tweet.created_at)%> ago</span></p>
					<p class="post-content"><%=tweet.content %></p>
				</div>

				<div class="col-sm-12" style="display: flex; justify-content: space-around; margin-top: 20px;">
					<ul class="post-links">
						<a href="/comments?tweet_id=<%=tweet.id%>"><li><span class="glyphicon glyphicon-comment g-links" aria-hidden="true"></span></li></a>

						<li><span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span></li>
						
						<li>
							<%=form_tag (toggle_path method:'post',tweet_id:tweet.id),remote:true do%>
								<a id="like_<%=tweet.id%>" data-remote="true" rel="nofollow" data-method="post" href="/toggle?tweet_id=<%=tweet.id%>" class="<%= tweet.like_string(current_user.id)%>"><span class="glyphicon glyphicon-heart g-links-heart"></span></a>
							<% end %>
						</li>

						<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" ><span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true">
						</span></a>
						<ul class="dropdown-menu">
							<% if tweet.user_id == current_user.id%>
			              		<li>Delete</li>
			              	<% else %>
			              		<li>Hide</li>
			              	<% end %>
			            </ul>
			            </li>

						</ul>
					</p>
				</div>
			</div>
		</div>

<style>
	.post-links{
		display: flex;
	}
	.post-links li{
		list-style: none;
	}
	.form-panel{
		box-shadow: 0px 1px lightgrey;
	}
	.round-image{
		border:1px solid <%=current_user.theme%>;
	}
	.like_link a{
		text-decoration: none!important;
		color: grey;
	}
	.Like:hover{
		color: red;
	}
</style>

<script>
</script>

app/views/pages/_signup.html.erb
<body>
<div class="fade">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading height"><b class="col-md-offset-5" style="font-size: 20px;">Sign Up</b></div>
        <div class="panel-body">
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>

            <div class="field form-group ">
              <%= f.label :username %><br />
              <%= f.text_field :username, autofocus: true , :class => 'form-control' ,:placeholder => 'Enter your username'%>
            </div>

            <div class="field form-group ">
              <%= f.label :email %><br />
              <%= f.email_field :email , :class => 'form-control',:placeholder => 'Enter your email'%>
            </div>

            <div class="field form-group ">
              <%= f.label :password %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off" , :class => 'form-control',:placeholder => 'Enter your password'%>
            </div>

            <div class="field form-group ">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off" , :class => 'form-control' ,:placeholder => 'Re-Enter your password'%>
            </div>

             <div class="actions form-group">
          <%= f.submit "Sign Up" , :class => 'btn btn-block btn-primary'%>
        </div>
      <% end %>
      </div>
      <div class="panel-footer">
      <%= render "devise/shared/links"%>
      </div>
      
    </div>
  </div>
</div>
</div>
</body>
<style>
  .height{
    height: 50px;
  }
  .fade{
    animation:fadein 1s;
  animation-timing-function:linear;
  animation-delay:0.1s;
  animation-fill-mode:forwards;
  animation-iteration-count: 1;
  }
  @keyframes fadein{
    from{
      opacity: 0.3;
    }
    to{
      opacity: 1;
    }
  }
  body{
    background:linear-gradient(rgba(0,0,0,0.7),
      rgba(0,0,0,0.7)),url('/bg5.jpg') no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
      overflow: hidden;
  }
</style>

app/views/pages/_trends.html.erb
	<div class="panel panel-default" style="margin-top: -15px; margin-left: -18px; margin-right: -18px;">
	<div class="row">
			<div class="col-sm-1" style="margin-top: 10px; margin-left: 10px;">
	  			<img src="/uploads/<%= User.find_by_id(trending.user_id).profile_picture %> " class="round-image" height="30px" width="30px">
	  			</img>
	  		</div>
	  		<div class="col-sm-10" style="margin-top: 10px;">
  				<p class="post-title"><span class="post-owner"><a href="/user/<%=User.find(trending.user_id).username%>"><%=User.find(trending.user_id).username%></a></span></p>	
  			</div>
  		</div>
		<div class="panel-body">
			<p class="post-content"><%=trending.content %></p>
		</div>
		<div class="panel-footer" style="background: transparent;">
		<ul style="display: flex; justify-content: space-around; margin-top: -10px; padding: 7px 7px 1px 7px;">
				<a href="/comments?tweet_id=<%=trending.id%>"><li style="list-style: none; margin-left: -20px;"><span class="glyphicon glyphicon-comment g-links" aria-hidden="true"></span></li></a>
			<li style="list-style: none; margin-left: -40px;">
				<%=form_tag (toggle_path method:'post',tweet_id:trending.id),remote:true do%>
						<a id="like_<%=trending.id%>" data-remote="true" rel="nofollow" data-method="post" href="/toggle?tweet_id=<%=trending.id%>" class="<%= trending.like_string(current_user.id)%>"><span class="glyphicon glyphicon-heart g-links-heart"></span></a>
						<% end %>
			</li>
			<li style="list-style: none; margin-left: -30px;">	
				<span id="trending_likes_count"><%=trending.likes.count%> Likes</span>
			</li>
		</ul>
	</div>
	</div>

app/views/pages/_whotofollow.html.erb
<div class="panel panel-default">
			<div class="panel-heading">
				<center><b>WHO TO FOLLOW</b></center>
			</div>
			<div class="panel-body">
				<%whotofollow.each do|users|%>
					<div class="row">
						<% if users.Can_follow users.id,current_user.id %>
							<% if !users.already_following users.id,current_user.id%>
								<div class="col-md-3">
									<img src="/uploads/<%=users.profile_picture%>" class="round-image wtfimage">
								</div>
								<div class="col-md-9 whotofollow">
									<div class="panel">
										<div class="panel-body">
										<a href="/user/<%=users.username%>"><%=users.username%></a>
										<form action="/user/pages/relation" method="POST">
										<input type="hidden" name="followee_id" value="<%=users.id%>"/>
		            					<button class="relation wtfrelation">
											<span class="relation-text">Follow</span>
										</button>
							</form>
										</div>
									</div>
								</div>
							<% end %>
						<% end %>
				</div>
		<% end %>
	</div>
</div>

<style type="text/css">
	.wtf-panel{
		border-bottom: 2px solid white;
	}
</style>

app/views/pages/developer.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-12 user-details">
            <div>
                <img src="/assets/AshishChauhan-f1a9b9ec198cb794080fd2b97cee52dfff87422ef437d4c5cdf753048752b287.jpg" alt="Ashish Chauhan" title="Ashish Chauhan" class="rounded float-left img-circle" style="width: 13%;">
            </div>
            <div class="user-info-block" style="background: transparent;">
                <div class="user-heading" style="margin-left: -30%;">
                    <h3 style="margin-top: -10px; opacity: 0.9"><b>Ashish Chauhan</b></h3>
                    <span class="help-block">NSIT, Delhi</span>
                </div>
                    	<div class="panel panel-primary">
                    		<div class="panel-heading" style="text-align: center;"><h3>ABOUT</h3></div>
                    		<div class="panel-body">
                    			<span style="font-size: 20px;">
                    				<table class="table">
									  <thead>
									    <tr>
									      <th>Certification</th>
									      <th>Year</th>
									      <th>Board/Institute</th>
									      <th>CGPA/%</th>
									    </tr>
									  </thead>
									  <tbody>
									    <tr>
									      <th scope="row">BE(ICE)</th>
									      <td>2019</td>
									      <td>Netaji Subhas Institute of Technology</td>
									      <td>71.64%</td>
									    </tr>
									    <tr>
									      <th scope="row">XII</th>
									      <td>2015</td>
									      <td>Central Board of Secondary Education</td>
									      <td>92.2%</td>
									    </tr>
									    <tr>
									      <th scope="row">X</th>
									      <td>2013</td>
									      <td>Central Board of Secondary Education</td>
									      <td>10</td>
									    </tr>
									  </tbody>
									</table>

	                    			<b> School Topper (2005 – 2015)</b> <br>&nbsp;&nbsp;- <i>Received Perfect Adarshian Award at Annual fest-2015 for excellent performance in studies for 10 consecutive years</i>
	                    			<br><br>

	                    			<b> School Prefect (Sep’14 – Mar’15)</b> <br>&nbsp;&nbsp;- <i>Part of the school students’ council, responsible for managing the various sports and cultural events of the school</i>
	                    			<br><br>

	                    			<b> Github Contributor</b>
	                    			<br>&nbsp;&nbsp;- <i>Contributed solutions of around 200+ coding problems via free repositories (GitHub profile - <a href="https://github.com/ashishc534">https://github.com/ashishc534</a>).</i>
	                    			<br><br>
	                        	</span>
	                        </div>
                    	</div>
                    	<div class="panel panel-primary">
                    		<div class="panel-heading" style="text-align: center;"><h3>STRENGTHS</h3></div>
                    		<div class="panel-body">
                    			<div class="row">
                    				<div class="col-md-4">
                    					<img src="https://www.cbronline.com/wp-content/uploads/2016/07/C.png" alt="C++" title="C++" style="width: 120px;">
                    				</div>
                					<div class="col-md-4">
                						<img src="http://www.christeck.de/wp/wp-content/uploads/christeck.de/ruby-2008.png"  alt="Ruby" title="Ruby" style="margin-left: 12px;">
                					</div>
                					<div class="col-md-4">
                    					<img src="https://pbs.twimg.com/profile_images/691206086955790336/CDMbA57p.png"  alt="Rails" title="Rails">
                    				</div> 
                    			</div>
                    			<div class="row">
                    				<div class="col-md-4">
                    					<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/200px-HTML5_logo_and_wordmark.svg.png"  alt="HTML" title="HTML">
                    				</div>
                					<div class="col-md-4">
                						<img src="https://www.wildcardcorp.com/blog/plone-mockup-patterns/@@download/image/js-logo-badge-512.png"  alt="JavaScript" title="JavaScript" style="width: 120px;">
                					</div>
                					<div class="col-md-4">
                    					<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-F9sZrnx-vk3mWjSV_BbhtYmjSg--o22FcCgyRrH49F390UGD"  alt="BootstrapCss" title="BootstrapCss">
                    				</div>
                    			</div>
                    		</div>
                    	</div>
                        	
                            
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<style type="text/css">
	body {background: #EAEAEA;}
.user-details {position: relative; padding: 0;}
.user-details .user-image {position: relative;  z-index: 1; text-align: center;}
 
.user-details .user-info-block {width: 100%; position: absolute; top: 55px; background: rgb(255, 255, 255); z-index: 0; padding-top: 35px;}
 .user-info-block .user-heading {width: 100%; text-align: center; margin: 10px 0 0;}
 .user-info-block .navigation {float: left; width: 100%; margin: 0; padding: 0; list-style: none; border-bottom: 1px solid #428BCA; border-top: 1px solid #428BCA;}
  .navigation li {float: left; margin: 0; padding: 0;}
   .navigation li a {padding: 20px 30px; float: left;}
   .navigation li.active a {background: #428BCA; color: #fff;}
 .user-info-block .user-body {float: left; padding: 5%; width: 90%;}
  .user-body .tab-content > div {float: left; width: 100%;}
  .user-body .tab-content h4 {width: 100%; margin: 10px 0; color: #333;}
  img{
  	width: 100px;
  	padding:20px;
  	border-radius: 40px;
  }

</style>

app/views/pages/explore.html.erb
<div class="row">
	<div class="col-md-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<center><b>Users Around The Globe</b></center>
			</div>
			<div class="panel-body">
				<%@users.each do |users|%>
					<div class="row">
						<div class="col-md-4" style="margin-top: 5px;">
							<img src="/uploads/<%=users.profile_picture%>" style="width: 50px;height: 50px;border-radius: 50%;">
						</div>
						<div class="panel" style="box-shadow: 0px 0.5px lightgrey">
							<div class="panel-body">
								<div class="col-md-8 whotofollow" style="margin-top: 2px;">
									<a href="/user/<%=users.username%>"><%=users.username%></a>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	
	<div class="col-md-6">
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<center><b>Trending Around The Globe</b></center>
			</div>
				<div class="panel-body">
						<% @feed.each do |tweet| %>
							<div id="tweets">
								<%= render 'post', tweet: tweet %>
							</div>
							<% end %>
							<div class="col-md-12">
	  							<center><img src="/image.jpg" height="25px" width="25px"><br><a href="#top"><p style="opacity: 0.7">Back to Top <span class="glyphicon glyphicon-arrow-up"></span></p></a></center>
		  					</div>
				</div>			
			</div>
	</div>

	<div class="col-md-3">
		<div class="panel panel-default">
  			<div class="panel-body">
				<p class="About"> <a href=#>@ 2017 Zitter</a>
					<a href=#>About</a>
					<a href=#>Help</a>
					<a href=#>Terms</a>
					<a href=#>Privacy</a>
					<a href=#>Cookies</a>
					<a href=#>Ads</a>
					<a href=#>Info</a>
					<a href=#>Brand</a>
					<a href=#>Blog</a>
					<a href=#>Status</a>
					<a href=#>Ads</a>
					<a href=#>Jobs</a>
					<a href=#>Advertise</a>
					<a href=#>Businesses</a>
					<a href=#>Media</a>
					<a href=#>Developers</a>
				</p>
			</div>
		</div>
	</div>	
</div>

app/views/pages/followers.html.erb
<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
	
		<% @followers.each do|followers|%>
			<%=render '/pages/followers' , followers:followers%>
		<% end %>
	</div>
</div>
	

app/views/pages/following.html.erb
<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
	
		<%@following.each do|following|%>
			<%= render '/pages/following' , following:following %>
		<% end %>
	</div>
</div>

app/views/pages/home.html.erb
<div class="row">
	<div class="col-xs-3">
		<div class="panel panel-default">
			<div class="panel-body" id="profile">
				<div style="width: 261px; height: 130px; background-color: <%=current_user.theme%>;"></div>
				<span><img src="/uploads/<%=current_user.profile_picture%>" class="profile profile_sketch" >
				<span class="post-owner"><a href="/user/<%=current_user.username%>"><%=current_user.username%></a></span>
				</span>
				<div id="User_acts">
				<a href="/user/<%=current_user.username%>" id="noOfposts"><span class="user-links">Posts</span>
					<div id="User_acts_count"><span id="tweets_count" style="margin-top: 0px;"><%=current_user.posts.length%></span></div></a>

				<a href="/user/<%=current_user.username%>/followers" id="noOffollowers"><span class="user-links">Followers</span>
				<div id="User_acts_count"><span id="followers_count"><%=current_user.passive_relationships.count%></span></div>
				</a>
				
				<a href="/user/<%=current_user.username%>/following" id="noOffollowees"><span class="user-links">Following</span>
				<div id="User_acts_count"><span id="following_count"><%= current_user.active_relationships.count%></span></div></a>
				</div>
			</div>		
		</div>
		
		<div class="panel panel-info">
			<div class="panel-heading">
				<center><b>Trending</b></center>
			</div>
			<div class="panel-body trending">
				<%@trending.each do|trending|%>
					<%= render 'trends',trending: trending %>
				<% end %>
			</div>
  			
		</div>
	</div>
	<div class="col-xs-6" style="margin-top: 20px;">
		<%= render '/posts/form' %><br><br>
			<%@feed.each do |tweet| %>
				<div id="tweets">
				<%= render 'post', tweet: tweet %>
				</div>
			<% end %>
		
		<div class="panel panel-default form-panel backToTop">
	  			<div class="panel-body row">
	  				<div class="col-sm-12">
	  					<center><img src="/image.jpg" height="25px" width="25px"><br><a href="#top"><p style="opacity: 0.7">Back to Top <span class="glyphicon glyphicon-arrow-up"></span></p></a></center>
	  				</div>
	  			</div>		
		</div>
		
	</div>
	<div class="col-xs-3">
		<div class="panel panel-default">
  			<div class="panel-body">
				<p class="About"> <a href=#>@ 2017 Zitter</a>
					<a href=#>About</a>
					<a href=#>Help</a>
					<a href=#>Terms</a>
					<a href=#>Privacy</a>
					<a href=#>Cookies</a>
					<a href=#>Ads</a>
					<a href=#>Info</a>
					<a href=#>Brand</a>
					<a href=#>Blog</a>
					<a href=#>Status</a>
					<a href=#>Ads</a>
					<a href=#>Jobs</a>
					<a href=#>Advertise</a>
					<a href=#>Businesses</a>
					<a href=#>Media</a>
					<a href=#>Developers</a>
				</p>
			</div>
		</div>
	</div>

</div>

<style>
	#profile{
		height: 280px;
		margin: 0;
		padding: 0;
	}
	.profile_sketch{
		width: 90px;
		height: 90px;
		margin-top: -40px;
		margin-left: 10px;
	}
	#profile span span{
		font-size: 120%;
	}
	#tweets_count{
		font-size: 18px;
		color: <%=current_user.theme%>;
		font-weight: bolder;
	}
	#followers_count{
		font-size: 18px;
		color: <%=current_user.theme%>;
		font-weight: bolder;
	}
	#following_count{
		font-size: 18px;
		color: <%=current_user.theme%>;
		font-weight: bolder;
	}
	#noOfposts{
		font-size: 15px;
		font-weight: bold;
		text-decoration: none;
		color: black;
	}
	#noOffollowers{
		font-size: 15px;
		font-weight: bold;
		text-decoration: none;
		color: black;
	}
	#noOffollowees{
		font-size: 15px;
		font-weight: bold;
		text-decoration: none;
		color: black;
	}
	#noOfposts:hover{
		color: <%=current_user.theme%>;
		opacity: 1.0;
	}
	#noOffollowees:hover{
		color: <%=current_user.theme%>;
		opacity: 1.0;
	}
	#noOffollowers:hover{
		color: <%=current_user.theme%>;
		opacity: 1.0;
	}
	#User_acts{
		margin-top: 10px;
		display: flex;
		justify-content: space-around;
	}
	#User_acts_count{
		margin-top: 4px;
		margin-left: -14px;
		display: flex;
		justify-content: space-around;
	}
	.user-links{
		opacity: 0.6;
		font-size: 13px;
	}
	.trending{
		word-wrap: break-word;
	}
</style>

app/views/pages/index.html.erb
<div class="container-index row fade">
	<div class="col-md-9 col-md-offset-2 ">
		<h1>Welcome to ZITTER.</h1>
		<p class="text">
			Connect With Your Buddies. Chat with Your Loved Ones.<br> 
			Share Your Adventures. Have Fun! <br>
			Just Like a Blog, But With Less Characters!
		</p>
	</div>
</div>
<div class="row fade">
	<a href="/users/sign_in"><button class="log-in"><b>Sign in</b></button></a>
	<a href="/users/sign_up"><button class="sign-up"><b>Sign Up</b></button></a>
</div>
	
	<div class="col-sm-12 fade">
		<p class="footer-links">About  Help  Blog  Status  Jobs  Terms  Privacy  Cookies  Ads info  Brand  Advertise  Business  Media  Developers  Directory  @  2017  Zitter</p>
	</div>
</div>
<% if !user_signed_in? %>
	<style>
		body{
			background:linear-gradient(rgba(0,0,0,0.7),
			rgba(0,0,0,0.7)),url('/bg.jpg') no-repeat center center fixed;
			-webkit-background-size: cover;
			-moz-background-size: cover;
			-o-background-size: cover;
			background-size: cover;
			overflow: hidden;
		}

		h1{
			color: white;
			font-weight: bold;
		}
		.container-index{
			margin-right: 15%;
			margin-left: 15%;
		}
		.text{
			color: white;
			font-weight: 300;
			font-size: 150%;
		}
		.footer-links{
			text-align: center;
			color: white;
			margin-top: 10%;
			font-size: 75%;
		}
		
		.log-in{
			margin-top: 50px;
			background:transparent;
			width: 40%;
			height: 150px;
			border: 2px solid lightblue;
			border-radius: 40px; 
			font-size: 100px;
			color: white;
			
		}
		.log-in:hover{
			background-color: rgba(0,0,0,0.5);
			color:white;
			border:2px solid white;
		}
		.sign-up{
			margin-top: 50px;
			background:transparent;
			width: 40%;
			height: 150px;
			border: 2px solid lightblue;
			border-radius: 40px; 
			font-size: 100px;
			color: white;
			float: right;
		}
		.sign-up:hover{
			background-color: rgba(0,0,0,0.5);
			color:white;
		}
		button{
			outline: none;
		}
		.fade{
    animation:fadein 1s;
  animation-timing-function:linear;
  animation-delay:0.1s;
  animation-fill-mode:forwards;
  animation-iteration-count: 1;
  }
  @keyframes fadein{
    from{
      opacity: 0.3;
    }
    to{
      opacity: 1;
    }
  }
  body{
    background:linear-gradient(rgba(0,0,0,0.7),
      rgba(0,0,0,0.7)),url('/bg5.jpg') no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
      overflow: hidden;
  }
	</style>
	
<% else %>
	<script>document.location = "/home" </script> 
<% end %> 

app/views/pages/likes.html.erb
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-xs-6" style="margin-top: 20px;">
		<% @feed.each do |tweet| %>
			<div id="tweets">
			<%= render 'post', tweet: tweet %>
			</div>
		<% end %>
	
		<div class="panel panel-default form-panel">
	  			<div class="panel-body row">
	  				<div class="col-sm-12">
	  					<center><img src="/image.jpg" height="25px" width="25px"><br><a href="#top"><p style="opacity: 0.7">Back to Top <span class="glyphicon glyphicon-arrow-up"></span></p></a></center>
	  				</div>
	  			</div>		
		</div>
</div>

app/views/pages/profile.html.erb
<div class="user-avatar">
	<img class="round" src="/uploads/<%=User.find_by_username(@username).profile_picture%>">
</div>
	<div class="row">
	<div class="col-md-3"></div>
	<div class="col-xs-6" style="margin-top: 20px;">
		<% @feed.each do |tweet| %>
			<div id="tweets">
			<%= render 'post', tweet: tweet %>
			</div>
		<% end %>
	
		<div class="panel panel-default form-panel">
	  			<div class="panel-body row">
	  				<div class="col-sm-12">
	  					<center><img src="/image.jpg" height="25px" width="25px"><br><a href="#top"><p style="opacity: 0.7">Back to Top <span class="glyphicon glyphicon-arrow-up"></span></p></a></center>
	  				</div>
	  			</div>		
		</div>
	</div>
	<div class="col-md-3">
		<%=render 'pages/whotofollow' , whotofollow:@whotofollow%>
	</div>
</div>

<style type="text/css">
	.whotofollow{
		margin-top: -10px;
	}
	.wtfrelation{
		right:0px;
		outline: none;
	}
	.wtfimage{
		height: 50px;
		width: 50px;
		border:1px solid #1da1f2;
		margin-top: 10px;
	}
</style>

app/views/pages/upload_image.html.erb
<div class="upload-image">
    <%= form_tag url_for(controller: :pages, action: :upload_image_submit), multipart: true do %>
    <%= file_field_tag :image %>
    <br>
    <%= submit_tag %>
    <% end %>
 </div>
  
  