config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :relationships
 
  root 'pages#index'
  post 'toggle' => 'likes#toggle_like'
  get '/home' => 'pages#home'
  get '/search' => 'posts#search'
  post 'user/pages/relation' => 'pages#relation'
  get '/user/:id' => 'pages#profile'
  get '/user/:id/following' => 'pages#following'
  get '/user/:id/followers' => 'pages#followers'
  get '/user/:id/likes' => 'pages#likes'
  post '/user/:id/pages/relation' => 'pages#relation'
  post '/theme_submit' => 'pages#theme_submit'
  post '/new' => 'comments#new'
  get '/comments' => 'comments#comment'
  get '/theme' => 'pages#theme'
  get '/explore' => 'pages#explore'
  get '/upload_image' => 'pages#upload_image'
  get '/upload_cover_image' =>'pages#upload_cover_image'
  post '/upload_image_submit' => 'pages#upload_image_submit'
  post '/upload_cover_image_submit' => 'pages#upload_cover_image_submit'
  
  get '/pages/developer'

end

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/nav_User' %>
<% else %>
  <%= render 'layouts/nav_Guest' %>
<% end %>

app/views/layouts/_nav_Guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <a class="navbar-brand" href="/"><b>Zitter</b></a>
        </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="/home">Home</a></li>
            
            <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

        <li><a href="/pages/developer">About Developer</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_nav_User.html.erb
<a name="top"></a>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      </div>

    <img class="navbar-brand brand-pos" src= "/image.jpg">
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/home"><span class="glyphicon glyphicon-home"></span><span class="nav-menu">Home</span></a></li>
        <li><a href="/explore"><span class="glyphicon glyphicon-flash"></span><span class="nav-menu">Explore</span></a></li>
        <li><a href="#2"><span class="glyphicon glyphicon-bell"></span><span class="nav-menu">Notifications</span></a></li>
        <li><a href="#3"><span class="glyphicon glyphicon-envelope"></span><span class="nav-menu">Messages</span></a></li>
      
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" ><img class="nav-image" src="/uploads/<%=current_user.profile_picture%>" height="25px" width="25px" ></a>
            
            <ul class="dropdown-menu">
              <li><a href="/user/<%=current_user.username%>">Profile</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Help</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to('Settings', edit_user_registration_path)%></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to('Add Profile Photo',upload_image_path)%></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to('Change Theme',theme_path)%></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to('Log Out',destroy_user_session_path,:method => :delete)%></li>
            </ul>
          </li>
        <li>
            <form class="navbar-form navbar-search navbar-right searchbar" role="Search" id="submitform" action="/user/profile">
              <div class="form-group">
               <input type="text" class="search-query form-control" name="search" placeholder="Search Users.."> <button class="search-button"><span class="search-text">Search</span></button>
              </div>
          </form>
        </li>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<script>
  $(".navbar [href]").each(function() {
    if (this.href == window.location.href) {
            $(this).addClass("active");
    }
});
  

</script>

<style>
  .active span{
    color: <%=current_user.theme%>;
  }
  .dropdown-menu li a:hover{
    color: <%=current_user.theme%>;
  }
  .nav-image{
    margin-top: 4px;
    border:1px solid <%=current_user.theme%>;
    border-radius: 5px;
  }
  .searchbar{
    margin-left: -20px;
  }
  .search-button{
    margin-top: 7px;
    margin-left: 5px;
    width: 80px;
    height: 30px;
    border:1px solid <%=current_user.theme%>;
    border-radius: 30px;
    outline: none;
  }
  .search-text{
    color:white;
  }
  .search-button:hover{
    border:1px solid white;
  }
  .search-button:hover .search-text{
    font-weight:bolder;
  }
  .dropdown-toggle:active, .open .dropdown-toggle {
        background:#FFF !important; 
        color:#000 !important;
    }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>

</head>
<body>
<% if notice %>
<script type="text/javascript">
	noty({text: '<%= notice %>',type: 'success',
    timeout: 2000});
   
</script>

<% end %>


<% if alert %>

<script type="text/javascript">
	noty({text: '<%= alert %>', type: 'error' ,timeout: 2000});
</script>
<% end %>

<%= render '/layouts/nav' %>

<div style="margin-top: 70px;">
<% if params[:id]!=nil %>
	<div style="display: flex; width: 100%; height: 250px;">
		<div class="profile-banner">
		</div>
	</div>
	<div class="user-avatar">
	<img class="round" src="/uploads/<%=User.find_by_username(@username).profile_picture%>">
</div>

	<div class="profile-banner-bottom">
		<div class="wrapper">
			<div class="links">
				<a href="/user/<%=params[:id]%>">Tweets
					<div class="user_data" style="margin-left: 0px;"><%=User.find_by_username(params[:id]).posts.count%></div>
				</a>
				<a href="/user/<%=params[:id]%>/following">Following
					<div class="user_data"><%=User.find_by_username(params[:id]).active_relationships.count%></div>
				</a>
				<a href="/user/<%=params[:id]%>/followers">Followers
					<div class="user_data"><%=User.find_by_username(params[:id]).passive_relationships.count%></div>
				</a>
				<a href="/user/<%=params[:id]%>/likes">Likes
					<div class="user_data" id="user_likes"><%=User.find_by_username(params[:id]).likes.count%></div>
				</a>
			</div>
			<% if params[:id]==current_user.username %>
				<button class="edit">
					<a href="/users/edit"><span>Edit Profile</span></a>
				</button>
			<% else %>

				<form action="pages/relation" method="POST">
				<input type="hidden" name="followee_id" value="<%=User.find_by_username(params[:id]).id %>"/>
	            	<% if Relationship.where(follower_id: current_user.id , followee_id: User.find_by_username(params[:id]).id).count>0 %>
						<button class="unmapping">
							<span class="unmapping-text">UnFollow</span>
						</button>
					<% else %>
						<button class="mapping">
							<span class="mapping-text">Follow</span>
						</button>
				
					<% end %>
				</form>
			<% end %>
		</div>
	</div>
</div>
<% end %>

<div class="container" style="margin-top: 80px;">
<%= yield %>	
</div>

</body>
</html>

<script>

$(".links [href]").each(function() {
		if (this.href == window.location.href) {
            $(this).addClass("onpage");
           }
});
</script>

<% if user_signed_in?%>
<style type="text/css">
.profile-banner{
	background-color: <%=current_user.theme%>
}
.onpage{
	border-bottom: 3px solid <%=current_user.theme%>;
}	
.onpage .user_data{
	color: <%=current_user.theme%>
}
.active{
	color: <%=current_user.theme%>
}
a{
	color: <%=current_user.theme%>;
}
button,.search-button{
	background-color: <%=current_user.theme%>
}
.edit:hover{
	background-color:<%=current_user.theme%>; 
}
.edit{
	border:1px solid <%=current_user.theme%>;	
}
.links a div:hover{
	color: <%=current_user.theme%>;
}
.unmapping{
	background-color: <%=current_user.theme%>;
	border:2px solid <%=current_user.theme%>;
}
.mapping-text{
	color:<%=current_user.theme%>;
}
.mapping:hover{
	background-color: <%=current_user.theme%>;
}
.mapping{
	border:2px solid <%=current_user.theme%>;
}
.relation:hover{
	background-color: <%=current_user.theme%>;
}
.relation-text{
	color: <%=current_user.theme%>;
}
.profile-short-banner{
	background-color: <%=current_user.theme%>;
}
</style>
<% end %>